# Generated by Django 5.0.1 on 2024-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(null=True, upload_to='property_photos/'),
        ),
    ]
