# Generated by Django 5.0.1 on 2024-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0003_remove_property_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
