# Generated by Django 5.0.1 on 2024-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0004_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Default Title', max_length=200, unique=True),
        ),
    ]
