# Generated by Django 5.0.1 on 2024-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0006_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='coordinates',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
