# Generated by Django 5.0.1 on 2024-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0007_property_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nearby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='coordinates',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.TextField(),
        ),
    ]
