# Generated by Django 5.0.1 on 2024-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0008_property_nearby_alter_property_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.TextField(),
        ),
    ]
