# Generated by Django 5.0.1 on 2024-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0010_alter_property_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='payment_plan',
            field=models.TextField(null=True),
        ),
    ]
