# Generated by Django 5.0.1 on 2024-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_property_price_details_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_details',
            field=models.TextField(default='empty', null=True),
        ),
    ]
