# Generated by Django 5.0.1 on 2024-02-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0014_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='video_file',
        ),
        migrations.AddField(
            model_name='image',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.land'),
        ),
        migrations.AddField(
            model_name='video',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.land'),
        ),
    ]
