# Generated by Django 5.0.1 on 2024-02-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0015_remove_land_video_file_image_land_video_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.property'),
        ),
        migrations.AlterField(
            model_name='video',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.property'),
        ),
    ]
