# Generated by Django 5.0.1 on 2024-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0016_alter_image_property_alter_video_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='dimensions',
            new_name='size',
        ),
        migrations.AddField(
            model_name='land',
            name='payment_plan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='titledeed',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
