# Generated by Django 5.0.1 on 2024-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0017_rename_dimensions_land_size_land_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='coordinates',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
